from Common import *

material_array_metal1 = [
    "Materials/Stone",
    "Materials/Copper",
    "Materials/Steel",
    "Materials/Aluminium",
    "Materials/StainlessSteel",
    "Materials/Titanium",
    "Materials/HardMetal",
    "Materials/Neutronium",
]

tier_material = [
    "Stone",
    "Copper",
    "Steel",
    "Aluminium",
    "StainlessSteel",
    "Titanium",
    "HardMetal",
    "Neutronium",
]


def extract_tier(something):
    if isinstance(something, int):
        return something

    if isinstance(something, dict):
        if "tier" in something:
            return something["tier"]

    if isinstance(something, str):
        for i in range(0, 7):
            if something.find(tier_material[i]) != -1:
                return i

    return 0


def named_material(name):
    list = [x for x in materials if x["name"] == name]
    if len(list) > 0:
        return list[0]
    return materials[0]


# https://ru.wikipedia.org/wiki/%D0%9D%D0%B8%D1%82%D1%80%D0%B8%D0%B4_%D0%B1%D0%BE%D1%80%D0%B0 BoronNitride
# https://en.wikipedia.org/wiki/Neutronium

# https://ru.wikipedia.org/wiki/%D0%A3%D0%B4%D0%B5%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F_%D1%82%D0%B5%D0%BF%D0%BB%D0%BE%D1%82%D0%B0_%D1%81%D0%B3%D0%BE%D1%80%D0%B0%D0%BD%D0%B8%D1%8F burning

materials = [
    {
        "name": "Hand",
        "Label": "Hand",
        "craftable": False,
        "IsExact": True,
    },
    {
        "name": "NoMaterial",
        "Label": "NoMaterial",
        "craftable": False,
    },
    {
        "name": "Computations",
        "Label": "Computations",
        "IsAbstract": True,
        "Description": [["calculations", "common"]],
    },
    {
        "name": "Heat",
        "Label": "Heat",
        "IsAbstract": True,
        "Unit": "J",
        "UnitS": "W",
        "UnitMul": 1,
    },
    {
        "name": "Electricity",
        "Label": "Electricity",
        "IsAbstract": True,
        "Unit": "J",
        "UnitS": "W",
        "UnitMul": 1,
    },
    {
        "name": "Kinetic",
        "Label": "Kinetic",
        "IsAbstract": True,
        "Unit": "J",
        "UnitS": "W",
        "UnitMul": 1,
    },
    {
        "name": "Copper",
        "Label": "Copper",
        "IsIngot": True,
        "IsDust": True,
        "SmeltLevel": 0,
        "IsBlock": True,
    },
    {
        "name": "Gold",
        "Label": "Gold",
        "IsDust": True,
        "IsIngot": True,
        "SmeltLevel": 0,
        "IsBlock": True,
    },
    {
        "name": "Superconductor",
        "Label": "Superconductor",
        "IsDust": True,
        "IsIngot": True,
        "SmeltLevel": 4,
        "IsBlock": True,
    },
    {
        "name": "Iron",
        "Label": "Iron",
        "IsDust": True,
        "IsIngot": True,
        "SmeltLevel": 0,
        "IsBlock": True,
    },
    {
        "name": "CircuitBoard",
        "Label": "Circuit Board",
        "IsExact": True,
        "mesh": "Models/BoardCrate",
        "Materials": ["Materials/Plastic"],
    },
    {
        "name": "AdvancedCircuitBoard",
        "Label": "Advanced Circuit Board",
        "IsExact": True,
        "mesh": "Models/BoardCrate",
        "Materials": ["Materials/DarkGreenPlastic"],
    },
    {
        "name": "Plastic",
        "Label": "Plastic",
        "IsExact": True,
    },
    {
        "name": "Steel",
        "Label": "Steel",
        "IsIngot": True,
        "IsDust": True,
        "SmeltLevel": 1,
        "IsBlock": True,
    },
    {
        "name": "Aluminium",
        "Label": "Aluminium",
        "IsDust": True,
        "IsIngot": True,
        "SmeltLevel": 3,
        "IsBlock": True,
    },
    {
        "name": "AluminiumOxide",
        "Label": "Aluminium Oxide",
        "IsDust": True,
        "SmeltLevel": 3,
        "IsBlock": True,
    },
    {
        "name": "StainlessSteel",
        "Label": "Stainless Steel",
        "SmeltLevel": 3,
        "IsIngot": True,
        "IsDust": True,
        "IsBlock": True,
    },
    {
        "name": "Titanium",
        "Label": "Titanium",
        "SmeltLevel": 4,
        "IsIngot": True,
        "IsDust": True,
        "IsBlock": True,
    },
    {
        "name": "TitaniumTetrachloride",
        "Label": "Titanium Tetrachloride",
        "SmeltLevel": 4,
        "IsFluid": True,
    },
    {
        "name": "TitaniumSponge",
        "Label": "Titanium Sponge",
        "SmeltLevel": 4,
        "IsExact": True,
    },
    {
        "name": "TitaniumOxide",
        "Label": "Titanium Oxide",
        "IsDust": True,
    },
    {
        "name": "PreparedTitaniumOxide",
        "Label": "Prepared Titanium Oxide",
        "IsDust": True,
    },
    {
        "name": "Zink",
        "Label": "Zink",
        "SmeltLevel": 0,
        "IsMetal": True,
        "IsDust": True,
        "IsBlock": True,
    },
    {
        "name": "Lithium",
        "Label": "Lithium",
        "SmeltLevel": 0,
        "IsMetal": True,
        "IsDust": True,
        "Burnable": {"BurnTime": 18 * 20, "HeatPerTick": 18, "TotalAsh": 0.06},
        "IsBlock": True,
    },
    {
        "name": "Tungsten",
        "Label": "Tungsten",
        "SmeltLevel": 4,
        "IsDust": True,
        "tier": 5,
    },
    {
        "name": "TungstenOxide",
        "Label": "Tungsten Oxide",
        "SmeltLevel": 4,
        "IsDust": True,
        "tier": 5,
    },
    {
        "name": "TungstenCarbide",
        "Label": "Tungsten Carbide",
        "IsDust": True,
        "tier": 5,
    },
    {
        "name": "HardMetal",
        "Label": "Hard Metal",
        "SmeltLevel": 4,
        "IsIngot": True,
        "IsDust": True,
        "tier": 5,
        "IsBlock": True,
    },
    {
        "name": "HotHardMetalIngot",
        "Label": "Hot Hard Metal Ingot",
        "SmeltLevel": 4,
        "IsExact": True,
        "tier": 5,
        "mesh": "Models/Ingot",
        "Materials": ["Materials/HotMetal"],
    },
    {
        "name": "HotNeutroniumIngot",
        "Label": "Hot Neutronium Ingot",
        "SmeltLevel": 4,
        "IsExact": True,
        "tier": 5,
        "mesh": "Models/Ingot",
        "Materials": ["Materials/VeryHotMetal"],
    }
    # ,{
    # 	"name": "Rubber",
    # 	"Label": "Rubber",
    # 	"SmeltLevel": 0,
    # 	"IsMetal": True,
    # 	"IsDust": True,
    # 	"tier": 2
    # }
    ,
    {
        "name": "Cobalt",
        "Label": "Cobalt",
        "SmeltLevel": 4,
        "IsDust": True,
        "tier": 5,
        "IsBlock": True,
    },
    {"name": "CobaltOxide", "Label": "Cobalt Oxide", "IsDust": True, "tier": 5},
    {
        "name": "Stone",
        "Label": "Stone",
        "tier": 0,
    },
    # },{
    # 	"name": "Bronze",
    # 	"Label": "Bronze",
    # 	"SmeltLevel": 2,
    # 	"IsMetal": True,
    # 	"IsDust": True,
    #
    # 	"IsBlock": True
    # },{
    # 	"name": "Brass",
    # 	"Label": "Brass",
    # 	"SmeltLevel": 2,
    # 	"IsMetal": True,
    # 	"IsDust": True,
    #
    # 	"IsBlock": True
    # },{
    # 	"name": "BrassDetails",
    # 	"Label": "Brass Parts",
    #
    # 	"IsExact": True,
    # 	"category": "Component"
    # },{
    # 	"name": "BrassReductor",
    # 	"Label": "Brass Reductor",
    #
    # 	"IsExact": True,
    # 	"category": "Component"
    # },
    {
        "name": "Cement",
        "Label": "Cement",
        "IsDust": True,
    },
    {
        "name": "Neutronium",
        "Label": "Neutronium",
        "IsIngot": True,
        "IsDust": True,
        "tier": 6,
    },
    {
        "name": "Chromium",
        "Label": "Chromium",
        "SmeltLevel": 0,
        "IsDust": True,
        "tier": 3,
    },
    {
        "name": "Plutonium",
        "Label": "Plutonium",
        "IsBlock": True,
        "IsDust": True,
    },
    {
        "name": "Uranium",
        "Label": "Uranium-238",
        "IsBlock": True,
        "IsDust": True,
    },
    {
        "name": "Uranium235",
        "Label": "Uranium-235",
        "IsBlock": True,
        "IsDust": True,
    },
    {
        "name": "Uranium233",
        "Label": "Uranium-233",
        "IsBlock": True,
        "IsDust": True,
    },
    {
        "name": "Uranium233Cell",
        "Label": "Uranium 233 Cell",
        "tier": 5,
        "IsExact": True,
        "max_count": 32,
        "Description": [["NuclearFuel", "common"]],
    },
    {
        "name": "UraniumCell",
        "Label": "Uranium Cell",
        "tier": 5,
        "IsExact": True,
        "max_count": 32,
        "Description": [["NuclearFuel", "common"]],
    },
    {
        "name": "PlutoniumCell",
        "Label": "Plutonium Cell",
        "tier": 5,
        "IsExact": True,
        "max_count": 32,
        "Description": [["NuclearFuel", "common"]],
    },
    {
        "name": "DepletedUraniumCell",
        "Label": "Depleted Uranium Cell",
        "tier": 5,
        "IsExact": True,
        "max_count": 32,
        "Description": [["NuclearFuel", "common"]],
    },
    {
        "name": "Thorium",
        "Label": "Thorium",
        "IsBlock": True,
        "IsDust": True,
    },
    {
        "name": "Sodium",
        "Label": "Sodium",
        "IsDust": True,
        "tier": 3,
        "IsBlock": True,
    },
    {
        "name": "Potassium",
        "Label": "Potassium",
        "IsDust": True,
        "tier": 3,
        "IsBlock": True,
    },
    {
        "name": "Sulfur",
        "Label": "Sulfur",
        "IsExact": True,
        "mesh": "Models/Dust",
    },
    {
        "name": "Steam",
        "Label": "Steam",
        "IsGas": True,
        "Unit": "J",
        "UnitMul": 1,
        "color": [1, 1, 1],
    },
    {
        "name": "Chlorine",
        "Label": "Chlorine",
        "IsGas": True,
        "tier": 4,
        "color": [1, 1, 0],
    },
    {
        "name": "Peat",
        "Label": "Peat",
        "IsExact": True,
        "Burnable": {"BurnTime": 400, "HeatPerTick": 10, "TotalAsh": 0.24},
        "tier": 0,
        "color": [0.2, 0.2, 0.0],
        "mesh": "Models/Piece",
    },
    {
        "name": "Coal",
        "Label": "Coal",
        "IsExact": True,
        "Burnable": {"BurnTime": 400, "HeatPerTick": 20, "TotalAsh": 0.12},
        "tier": 0,
        "color": [0.0, 0.0, 0.0],
        "mesh": "Models/Piece",
    },
    {
        "name": "Coke",
        "Label": "Coke",
        "IsExact": True,
        "Burnable": {"BurnTime": 400 / 1.5, "HeatPerTick": 30 * 1.5, "TotalAsh": 0.06},
        "color": [0.0, 0.0, 0.0],
        "mesh": "Models/Piece",
    },
    {
        "name": "Creosote",
        "Label": "Creosote",
        "IsGas": True,
        "Burnable": {
            "BurnTime": 400,
            "HeatPerTick": 20,
        },
        "tier": 0,
        "color": [0.0, 0.0, 0.0],
        "mesh": "Models/Piece",
    },
    {
        "name": "ProducerGas",
        "Label": "Producer Gas",
        "IsGas": True,
        "Burnable": {"BurnTime": 400, "HeatPerTick": 80, "TotalAsh": 0},
        "color": [1, 1, 1],
    },
    {
        "name": "CarbonMonoxide",
        "Label": "Carbon Monoxide",
        "IsGas": True,
        "Burnable": {"BurnTime": 200, "HeatPerTick": 40, "TotalAsh": 0},
        "color": [1, 1, 1],
    },
    {"name": "Ash", "Label": "Ash", "IsDust": True, "tier": 0},
    {
        "name": "Hydrogen",
        "Label": "Hydrogen",
        "IsGas": True,
        "Burnable": {"BurnTime": 400, "HeatPerTick": 160, "TotalAsh": 0},
        "tier": 2,
        "color": [0.2, 0.2, 0.5],
    },
    {
        "name": "Methane",
        "Label": "Methane",
        "IsGas": True,
        "Burnable": {"BurnTime": 400, "HeatPerTick": 40, "TotalAsh": 0},
        "tier": 2,
        "color": [0.5, 0.2, 0.2],
    },
    {
        "name": "Ethylene",
        "Label": "Ethylene",
        "IsGas": True,
        "Burnable": {"BurnTime": 400, "HeatPerTick": 50, "TotalAsh": 0},
        "tier": 2,
        "color": [0.2, 0.5, 0.2],
    },
    # ,{
    # 	"name": "Nickel",
    # 	"Label": "Nickel",
    # 	"SmeltLevel": 0,
    # 	"IsMetal": True,
    # 	"IsDust": True,
    # 	"IsLiquidMetal": True,
    # 	"IsBlock": True,
    # 	"tier": 3
    # }
    {"name": "Water", "Label": "Water", "IsFluid": True, "tier": 0},
    {
        "name": "Glass",
        "Label": "Glass",
        "IsExact": True,
        "tier": 0,
    },
    {
        "name": "Lense",
        "Label": "Lense",
        "IsExact": True,
        "tier": 0,
    },
    {
        "name": "Organics",
        "Label": "Organics",
        "IsExact": True,
        "tier": 0,
        "mesh": "Models/Piece",
        "Description": [["Organics", "common"]],
    },
    {
        "name": "Biomass",
        "Label": "Biomass",
        "IsFluid": True,
    },
    {
        "name": "Clay",
        "Label": "Clay",
        "tier": 0,
        "IsExact": True,
        "mesh": "Models/Piece",
    },
    {
        "name": "OreWater",
        "Label": "Ore Water",
        "IsFluid": True,
    },
    {
        "name": "RareEarthElement",
        "Label": "Rare Earth Element",
        "IsExact": True,
        "mesh": "Models/Dust",
    },
    {
        "name": "Log",
        "Label": "Log",
        "IsExact": True,
        "tier": 0,
        "Burnable": {"BurnTime": 400, "HeatPerTick": 10, "TotalAsh": 0.24},  # 5.5kwh
        "color": [0.9, 0.9, 0.9],
    },
    {
        "name": "StoneLog",
        "Label": "Stone Log",
        "IsExact": True,
        "tier": 0,
        "Burnable": {"BurnTime": 800, "HeatPerTick": 10, "TotalAsh": 0.5},
    },
    {
        "name": "Plank",
        "Label": "Plank",
        "IsExact": True,
        "tier": 0,
        "Burnable": {"BurnTime": 100, "HeatPerTick": 10, "TotalAsh": 0.24},
    },
    {"name": "Silicon", "Label": "Silicon", "IsExact": True, "tier": 3},
    {"name": "SiliconWafer", "Label": "Silicon Wafer", "IsExact": True, "tier": 4},
    {"name": "SulfuricAcid", "Label": "Sulfuric Acid", "IsFluid": True, "tier": 3},
    {
        "name": "RawOil",
        "Label": "Raw Oil",
        "IsFluid": True,
        "tier": 0,
        "Burnable": {"BurnTime": 400, "HeatPerTick": 10, "TotalAsh": 0},
        "color": [0.1, 0.1, 0.1],
    },
    {"name": "MineralWater", "Label": "Mineral Water", "IsFluid": True, "tier": 0},
    {
        "name": "Gasoline",
        "Label": "Gasoline",
        "IsGas": True,
        "tier": 1,
        "Burnable": {"BurnTime": 400, "HeatPerTick": 40, "TotalAsh": 0},
        "color": [0.5, 0.5, 0.2],
    },
    {
        "name": "HeavyOil",
        "Label": "Heavy Oil",
        "IsGas": True,
        "tier": 2,
        "Burnable": {"BurnTime": 400, "HeatPerTick": 20, "TotalAsh": 0},
        "color": [0.2, 0.5, 0.2],
    },
    {"name": "Battery", "Label": "Battery", "IsExact": True, "tier": 3},
    {"name": "SiliconOxide", "Label": "Silicon Oxide", "IsExact": True, "tier": 1},
    {"name": "Pumpkin", "Label": "Pumpkin", "IsExact": True, "tier": 0},
    {"name": "Oxygen", "Label": "Oxygen", "IsGas": True, "tier": 4},
    {"name": "Nitrogen", "Label": "Nitrogen", "IsGas": True, "tier": 4},
    {"name": "ChromiumOxide", "Label": "Chromium Oxide", "IsDust": True, "tier": 3},
    {
        "name": "PotassiumChloride",
        "Label": "Potassium Chloride",
        "IsDust": True,
        "tier": 3,
    },
    {"name": "Beryllium", "Label": "Beryllium", "IsDust": True, "tier": 4},
    {"name": "Yttrium", "Label": "Yttrium", "IsDust": True, "tier": 3},
    {"name": "Helium", "Label": "Helium", "IsGas": True, "IsPlasma": True, "tier": 4},
    {"name": "Salt", "Label": "Salt", "IsDust": True, "tier": 4},
    {"name": "PortalBase", "Label": "Portal Base", "IsExact": True, "tier": 2},
    {"name": "Signal", "Label": "Signal", "IsExact": True},
    {
        "name": "CopperWire",
        "Label": "Copper Wire",
        "max_count": 64,
        "IsExact": True,
        "category": "Parts",
        "mesh": "Models/WireCrate",
        "Materials": ["Materials/CopperWiresOnCrate"],
    },
    {
        "name": "GoldWire",
        "Label": "Gold Wire",
        "max_count": 64,
        "IsExact": True,
        "category": "Parts",
        "mesh": "Models/WireCrate",
        "Materials": ["Materials/GoldWiresOnCrate"],
    },
    {
        "name": "SuperconductorWire",
        "Label": "Superconductor Wire",
        "max_count": 64,
        "IsExact": True,
        "category": "Parts",
        "mesh": "Models/WireCrate",
        "Materials": ["Materials/SuperWiresOnCrate"],
    },
    {
        "name": "Circuit",
        "Label": "Circuit",
        "max_count": 32,
        "IsExact": True,
        "category": "Parts",
        "Description": [["Circuit", "common"]],
        "mesh": "Models/CircuitCrate",
    },
    {
        "name": "AdvancedCircuit",
        "Label": "Advanced Circuit",
        "max_count": 32,
        "IsExact": True,
        "category": "Parts",
        "Description": [["Circuit", "common"]],
        "mesh": "Models/Circuit2Crate",
    },
    {
        "name": "Processor",
        "Label": "Processor",
        "max_count": 32,
        "IsExact": True,
        "category": "Parts",
        "Description": [["Circuit", "common"]],
        "mesh": "Models/Circuit3Crate",
    },
    {
        "name": "QuantumCircuit",
        "Label": "Quantum Circuit",
        "max_count": 32,
        "IsExact": True,
        "category": "Parts",
        "Description": [["Circuit", "common"]],
        "mesh": "Models/Circuit3Crate",
    },
    {
        "name": "QuantumProcessor",
        "Label": "Quantum Processor",
        "max_count": 32,
        "IsExact": True,
        "category": "Parts",
        "Description": [["Circuit", "common"]],
        "mesh": "Models/Circuit3Crate",
    },
    {
        "name": "QuantumCore",
        "Label": "Quantum Core",
        "max_count": 32,
        "IsExact": True,
        "category": "Parts",
        "mesh": "Models/Circuit3Crate",
    },
    {
        "name": "QuantumBrain",
        "Label": "Quantum Brain",
        "max_count": 32,
        "IsExact": True,
        "category": "Parts",
        "Description": [["Circuit", "common"]],
        "mesh": "Models/Circuit3Crate",
    },
    {
        "name": "Cell",
        "Label": "Cell",
        "max_count": 32,
        "IsExact": True,
        "category": "Parts",
    },
    {
        "name": "Catalyst",
        "Label": "Catalyst Cell",
        "max_count": 32,
        "IsExact": True,
    },
    {
        "name": "UltimateCatalyst",
        "Label": "Ultimate Catalyst Cell",
        "max_count": 32,
        "IsExact": True,
    },
    {
        "name": "MothershipPing",
        "Label": "Mothership Ping",
        "max_count": 32,
        "IsExact": True,
    },
    {
        "name": "ControlCell",
        "Label": "Control Cell",
        "max_count": 32,
        "IsExact": True,
    },
    {
        "name": "ReflectorCell",
        "Label": "Reflector Cell",
        "max_count": 32,
        "IsExact": True,
    },
    {
        "name": "ThoriumCell",
        "Label": "Thorium Cell",
        "max_count": 32,
        "IsExact": True,
    },
    {
        "name": "MixedOxideCell",
        "Label": "Mixed-Oxide Cell",
        "max_count": 32,
        "IsExact": True,
    },
    {
        "name": "RutileCrystal",
        "Label": "Rutile Crystal",
        "max_count": 32,
        "IsExact": True,
        "category": "Mineral",
    },
    {
        "name": "UraniniteCrystal",
        "Label": "Uraninite Crystal",
        "max_count": 32,
        "IsExact": True,
        "category": "Mineral",
    },
    {
        "name": "UraniniteCluster",
        "Label": "Uraninite Cluster",
        "max_count": 32,
        "IsExact": True,
        "category": "Mineral",
    },
    {
        "name": "Cinnabar",
        "Label": "Cinnabar",
        "max_count": 32,
        "IsDust": True,
        "category": "Mineral",
    },
    {
        "name": "CinnabarCrystal",
        "Label": "Cinnabar Crystal",
        "max_count": 32,
        "IsExact": True,
        "category": "Mineral",
    },
    {
        "name": "CinnabarCluster",
        "Label": "Cinnabar Cluster",
        "max_count": 32,
        "IsExact": True,
        "category": "Mineral",
    },
    {
        "name": "Malachite",
        "Label": "Malachite",
        "max_count": 32,
        "IsDust": True,
        "category": "Mineral",
    },
    {
        "name": "MalachiteCrystal",
        "Label": "Malachite Crystal",
        "max_count": 32,
        "IsExact": True,
        "category": "Mineral",
    },
    {
        "name": "MalachiteCluster",
        "Label": "Malachite Cluster",
        "max_count": 32,
        "IsExact": True,
        "category": "Mineral",
    },
    {
        "name": "Mercury",
        "Label": "Mercury",
        "IsFluid": True,
    },
    {
        "name": "FilteringCell",
        "Label": "Filtering Cell",
        "max_count": 32,
        "IsExact": True,
    },
    {"name": "Boron", "Label": "Boron", "IsDust": True, "tier": 4},
    {
        "name": "Borax",
        "Label": "Borax",
        "max_count": 32,
        "IsDust": True,
        "category": "Mineral",
    },
    {
        "name": "Emerald",
        "Label": "Emerald",
        "max_count": 32,
        "IsExact": True,
        "IsDust": True,
        "category": "Mineral",
    },
    {
        "name": "Capacity",
        "Label": "Capacity",
        "craftable": False,
        "IsExact": True,
        "category": "Signal",
    },
    {
        "name": "InputError",
        "Label": "Input Error",
        "craftable": False,
        "IsExact": True,
        "category": "Signal",
    },
    {
        "name": "OutputError",
        "Label": "Output Error",
        "craftable": False,
        "IsExact": True,
        "category": "Signal",
    },
    {
        "name": "Progress",
        "Label": "Progress",
        "craftable": False,
        "IsExact": True,
        "category": "Signal",
    },
    {
        "name": "SwitchedOn",
        "Label": "Switched On",
        "craftable": False,
        "IsExact": True,
        "category": "Signal",
    },
]

import string

for a in list(string.ascii_uppercase):
    materials.append(
        {
            "name": a,
            "Label": a,
            "IsExact": True,
            "craftable": False,
            "category": "Signal",
        }
    )

materials.append(
    {
        "name": "ErrorString",
        "Label": "Error String",
        "IsExact": True,
        "craftable": False,
    }
)
